import type { CSSProperties } from "react";

// 로그인/회원가입 등 인증 화면 공통 스타일 (ZCS 파란색 계열)
const font =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans KR', Arial, sans-serif";

export const authStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    flexWrap: "wrap-reverse", // 화면이 좁으면 브랜드 패널이 폼 아래로
    background: "#f4f6f9",
    color: "#0f172a",
    fontFamily: font,
  },

  // 왼쪽 브랜드 패널
  brandPanel: {
    flex: "1 1 420px",
    minWidth: 0, // 좁은 화면에서 가로로 넘치지 않게
    minHeight: 320,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "40px 48px",
    boxSizing: "border-box",
    backgroundColor: "#173357",
    backgroundImage:
      "radial-gradient(ellipse at 0% 0%, rgba(255,255,255,0.12), transparent 55%), radial-gradient(ellipse at 100% 100%, rgba(57,135,229,0.25), transparent 50%)",
    color: "#ffffff",
  },
  brandLogo: {
    display: "inline-flex",
    alignItems: "center",
    gap: 12,
    padding: 0,
    border: "none",
    background: "none",
    color: "#ffffff",
    cursor: "pointer",
    fontFamily: font,
  },
  brandMark: {
    fontSize: 32,
    fontWeight: 900,
    letterSpacing: "0.5px",
  },
  brandName: {
    fontSize: 13,
    fontWeight: 700,
    opacity: 0.8,
    textAlign: "left",
    lineHeight: 1.3,
  },
  brandHeadline: {
    margin: "0 0 14px",
    fontSize: 30,
    fontWeight: 800,
    lineHeight: 1.35,
    letterSpacing: "-0.5px",
  },
  brandDesc: {
    margin: "0 0 28px",
    fontSize: 15,
    lineHeight: 1.7,
    color: "rgba(255,255,255,0.72)",
    maxWidth: 420,
  },
  brandList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  brandItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 14,
    color: "rgba(255,255,255,0.88)",
  },
  brandFoot: {
    fontSize: 12,
    color: "rgba(255,255,255,0.5)",
  },

  // 오른쪽 폼 영역
  formSide: {
    flex: "1 1 480px",
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "48px 24px",
    boxSizing: "border-box",
  },
  formBox: {
    width: "100%",
    maxWidth: 380,
  },
  title: {
    margin: 0,
    fontSize: 26,
    fontWeight: 900,
    letterSpacing: "-0.3px",
  },
  subtitle: {
    margin: "6px 0 28px",
    fontSize: 14,
    color: "#64748b",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  label: {
    fontSize: 13,
    fontWeight: 700,
    color: "#334155",
  },
  inputWrap: {
    position: "relative",
  },
  input: {
    width: "100%",
    height: 46,
    padding: "0 14px",
    boxSizing: "border-box",
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    background: "#ffffff",
    color: "#0f172a",
    fontSize: 15,
    outline: "none",
    transition: "border-color 0.15s, box-shadow 0.15s",
    fontFamily: font,
  },
  inputFocus: {
    borderColor: "#1f4e8c",
    boxShadow: "0 0 0 3px rgba(31, 78, 140, 0.12)",
  },
  eyeButton: {
    position: "absolute",
    right: 6,
    top: "50%",
    transform: "translateY(-50%)",
    width: 34,
    height: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    background: "none",
    color: "#94a3b8",
    cursor: "pointer",
  },
  submit: {
    height: 48,
    marginTop: 4,
    border: "none",
    borderRadius: 8,
    background: "#173357",
    color: "#ffffff",
    fontSize: 15,
    fontWeight: 800,
    cursor: "pointer",
    transition: "background 0.15s",
    fontFamily: font,
  },
  submitHover: {
    background: "#0f2440",
  },
  linkRow: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
    fontSize: 13,
    color: "#cbd5e1",
  },
  linkButton: {
    padding: 0,
    border: "none",
    background: "none",
    color: "#64748b",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: font,
  },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    margin: "24px 0",
    color: "#94a3b8",
    fontSize: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    background: "#e2e8f0",
  },
  // 회원가입: 이름 | 아이디 두 칸 (좁으면 한 칸씩)
  fieldRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 16,
  },
  hint: {
    fontSize: 12,
    color: "#94a3b8",
    lineHeight: 1.5,
  },
  hintOk: {
    color: "#16a34a",
  },
  hintError: {
    color: "#dc2626",
  },
  checkList: {
    display: "flex",
    flexWrap: "wrap",
    gap: "4px 12px",
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  checkItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: "#94a3b8",
    transition: "color 0.15s",
  },
  signupRow: {
    marginTop: 28,
    paddingTop: 20,
    borderTop: "1px solid #e2e8f0",
    textAlign: "center",
    fontSize: 14,
    color: "#64748b",
  },
  signupLink: {
    marginLeft: 6,
    padding: 0,
    border: "none",
    background: "none",
    color: "#1f4e8c",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    fontFamily: font,
  },
};
