import type { CSSProperties } from "react";

const font =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans KR', Arial, sans-serif";

export const fileUploadStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f4f6f9",
    color: "#0f172a",
    fontFamily: font,
  },
  content: {
    maxWidth: 880,
    margin: "0 auto",
    padding: "32px 32px 56px",
    boxSizing: "border-box",
  },
  backButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 16,
    padding: 0,
    border: "none",
    background: "none",
    color: "#475569",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: font,
  },
  title: {
    margin: 0,
    fontSize: 26,
    fontWeight: 900,
    letterSpacing: "-0.3px",
  },
  subTitle: {
    margin: "6px 0 24px",
    fontSize: 14,
    color: "#64748b",
    lineHeight: 1.6,
  },

  // 업로드 카드
  dropCard: {
    borderRadius: 12,
    backgroundColor: "#ffffff",
    border: "1px solid #e2e8f0",
    padding: 20,
  },
  dropZone: {
    borderRadius: 10,
    border: "2px dashed #cbd5e1",
    padding: "44px 24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#f8fafc",
    textAlign: "center",
    cursor: "pointer",
    outline: "none",
    transition: "border-color 0.15s, background-color 0.15s",
  },
  dropZoneActive: {
    borderColor: "#1f4e8c",
    backgroundColor: "rgba(31, 78, 140, 0.05)",
  },
  dropIcon: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(31, 78, 140, 0.08)",
    color: "#1f4e8c",
    marginBottom: 4,
  },
  dropTitle: {
    fontSize: 16,
    fontWeight: 800,
    color: "#0f172a",
  },
  dropHelper: {
    fontSize: 13,
    color: "#64748b",
  },
  pickButton: {
    marginTop: 6,
    height: 38,
    padding: "0 16px",
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    background: "#ffffff",
    color: "#1e293b",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: font,
  },
  formatRow: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
    marginTop: 10,
  },
  formatChip: {
    padding: "3px 10px",
    borderRadius: 999,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    color: "#475569",
    fontSize: 12,
    fontWeight: 700,
  },

  // 선택한 파일 목록
  listHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    margin: "20px 2px 10px",
    fontSize: 14,
    fontWeight: 800,
  },
  textButton: {
    padding: 0,
    border: "none",
    background: "none",
    color: "#64748b",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: font,
  },
  fileList: {
    borderRadius: 10,
    border: "1px solid #e2e8f0",
    overflow: "hidden",
  },
  fileRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderBottom: "1px solid #f1f5f9",
  },
  fileRowLast: {
    borderBottom: "none",
  },
  fileIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    background: "#f1f5f9",
    color: "#475569",
  },
  fileMeta: {
    flex: 1,
    minWidth: 0,
  },
  fileName: {
    fontSize: 14,
    fontWeight: 700,
    color: "#0f172a",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fileSize: {
    marginTop: 2,
    fontSize: 12,
    color: "#94a3b8",
  },
  removeBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    border: "none",
    background: "transparent",
    color: "#94a3b8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },

  actionRow: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: 16,
  },
  primaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    height: 44,
    padding: "0 22px",
    border: "none",
    borderRadius: 8,
    background: "#173357", // ZCS 어두운 파란색
    color: "#ffffff",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    fontFamily: font,
  },
  primaryBtnDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },

  // 카드 아래 안내
  tips: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    margin: "18px 2px 0",
    padding: 0,
    listStyle: "none",
  },
  tip: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    color: "#64748b",
    lineHeight: 1.5,
  },
};
