export const scanResultStyles = {
  page: {
    minHeight: "100vh",
    background: "#f4f6f9",
    color: "#0f172a",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans KR', Arial, sans-serif",
  },
  // Topbar 아래 본문 (가운데 정렬)
  content: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "28px 32px 56px",
    boxSizing: "border-box" as const,
  },
  backLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
    padding: 0,
    border: "none",
    background: "none",
    color: "#64748b",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    flexWrap: "wrap" as const,
    gap: 16,
    marginBottom: 24,
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap" as const,
    justifyContent: "flex-end",
  },
  title: {
    margin: 0,
    fontSize: 26,
    fontWeight: 900,
    letterSpacing: "-0.3px",
  },
  subtitle: {
    margin: "6px 0 0",
    color: "#64748b",
    fontSize: 14,
    lineHeight: 1.6,
  },
  button: {
    height: 40,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#1e293b",
    borderRadius: 8,
    padding: "0 14px",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  primaryActionButton: {
    height: 40,
    border: "1px solid #173357",
    background: "#173357", // ZCS 어두운 파란색
    color: "#ffffff",
    borderRadius: 8,
    padding: "0 16px",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  primaryButton: {
    height: 38,
    border: "1px solid #173357",
    background: "#173357",
    color: "#ffffff",
    borderRadius: 8,
    padding: "0 14px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  disabledButton: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  reportHero: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(360px, 1fr))",
    gap: 18,
    marginBottom: 18,
  },
  // 위험 상태 카드 — 흰 바탕 + 왼쪽 색 띠 (색은 riskStatus에서)
  riskCardBase: {
    borderRadius: 10,
    padding: "24px 26px",
    display: "flex",
    gap: 16,
    alignItems: "center",
    background: "#ffffff",
    borderLeftWidth: 4,
  },
  riskIconBase: {
    width: 48,
    height: 48,
    borderRadius: "50%",
    background: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  riskLabelBase: {
    display: "inline-flex",
    alignItems: "center",
    height: 24,
    padding: "0 10px",
    borderRadius: 999,
    background: "#ffffff",
    fontSize: 12,
    fontWeight: 800,
    marginBottom: 8,
  },
  riskTitleBase: {
    margin: 0,
    fontSize: 21,
    fontWeight: 900,
    letterSpacing: "-0.3px",
  },
  riskText: {
    margin: "6px 0 0",
    color: "#475569",
    fontSize: 14,
    lineHeight: 1.6,
  },
  insightPanel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    padding: "20px 22px",
  },
  insightTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 800,
  },
  ratioBar: {
    height: 10,
    borderRadius: 999,
    background: "#e2e8f0",
    overflow: "hidden",
    marginTop: 14,
  },
  ratioFillBase: {
    height: "100%",
  },
  insightLine: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 12,
    color: "#475569",
    fontSize: 13,
    lineHeight: 1.5,
  },
  // 정책 판정 — 흰 바탕 + 왼쪽 색 띠 (색은 판정 결과에서)
  policyPanel: {
    borderRadius: 10,
    padding: "22px 24px",
    marginBottom: 18,
    background: "#ffffff",
    borderLeftWidth: 4,
  },
  policyHeader: {
    display: "flex",
    gap: 14,
    alignItems: "center",
  },
  policyIcon: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  policyBadge: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: 12,
    fontWeight: 800,
    color: "#64748b",
    marginBottom: 2,
  },
  policyTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 900,
    letterSpacing: "-0.3px",
  },
  policySummary: {
    margin: "4px 0 0",
    color: "#475569",
    fontSize: 14,
    lineHeight: 1.6,
  },
  policyGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 12,
    marginTop: 18,
  },
  policyRuleBox: {
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    background: "#ffffff",
    overflow: "hidden",
  },
  policyRuleTitle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    margin: 0,
    padding: "11px 14px",
    borderBottom: "1px solid #e2e8f0",
    background: "#f8fafc",
    color: "#0f172a",
    fontSize: 13,
    fontWeight: 800,
  },
  policyRuleItem: {
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    padding: "11px 14px",
    borderBottom: "1px solid #f1f5f9",
    color: "#334155",
    fontSize: 13,
    lineHeight: 1.5,
  },
  policyEmptyText: {
    margin: 0,
    padding: "12px 14px",
    color: "#64748b",
    fontSize: 13,
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(120px, 1fr))",
    gap: 12,
    marginBottom: 22,
  },
  summary: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "16px 18px",
    minHeight: 92,
    boxSizing: "border-box" as const,
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: 800,
    color: "#64748b",
  },
  summaryValue: {
    marginTop: 8,
    fontSize: 30,
    fontWeight: 900,
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "360px minmax(0, 1fr)",
    gap: 18,
    alignItems: "start",
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    overflow: "hidden",
  },
  panelTitle: {
    margin: 0,
    padding: "16px 20px",
    borderBottom: "1px solid #e2e8f0",
    fontSize: 16,
    fontWeight: 800,
  },
  fixItem: {
    padding: "14px 20px",
    borderBottom: "1px solid #f1f5f9",
  },
  packageType: {
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    padding: "0 8px",
    borderRadius: 999,
    background: "#f1f5f9",
    color: "#475569",
    fontSize: 11,
    fontWeight: 700,
  },
  guideBox: {
    marginTop: 10,
    padding: "9px 12px",
    borderRadius: 6,
    background: "#0f172a",
    color: "#e2e8f0",
    fontSize: 12,
    lineHeight: 1.5,
    wordBreak: "break-word" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: 13,
  },
  tableWrap: {
    maxHeight: 420,
    overflow: "auto",
  },
  fixPlanGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 14,
    padding: "0 20px 20px",
  },
  fixPlanColumn: {
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    overflow: "hidden",
    background: "#ffffff",
  },
  fixPlanColumnHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    padding: "11px 14px",
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
    fontSize: 13,
    fontWeight: 800,
  },
  planItem: {
    padding: "13px 14px",
    borderBottom: "1px solid #f1f5f9",
    fontSize: 13,
  },
  planMeta: {
    display: "flex",
    flexWrap: "wrap" as const,
    alignItems: "center",
    gap: 8,
    marginTop: 6,
    color: "#64748b",
    fontSize: 12,
  },
  smallPill: {
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    padding: "0 8px",
    borderRadius: 999,
    background: "#f1f5f9",
    color: "#475569",
    fontSize: 11,
    fontWeight: 700,
  },
  tableHeaderText: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap" as const,
    gap: 12,
    padding: "18px 20px",
  },
  sectionHeading: {
    margin: 0,
    fontSize: 16,
    fontWeight: 800,
  },
  sectionDescription: {
    margin: "4px 0 0",
    color: "#64748b",
    fontSize: 13,
    lineHeight: 1.5,
  },
  countPill: {
    display: "inline-flex",
    alignItems: "center",
    height: 28,
    padding: "0 10px",
    borderRadius: 999,
    background: "#f1f5f9",
    color: "#334155",
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap" as const,
  },
  th: {
    position: "sticky" as const, // 표를 스크롤해도 머리글 고정
    top: 0,
    zIndex: 1,
    textAlign: "left" as const,
    background: "#f8fafc",
    color: "#64748b",
    padding: "11px 20px",
    borderTop: "1px solid #e2e8f0",
    borderBottom: "1px solid #e2e8f0",
    fontSize: 12,
    fontWeight: 700,
  },
  td: {
    padding: "12px 20px",
    borderBottom: "1px solid #f1f5f9",
    verticalAlign: "middle" as const,
  },
  componentName: {
    maxWidth: 520,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  mono: {
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace",
  },
};

export type ScanResultStyles = typeof scanResultStyles;
